"""empty message

Revision ID: 6c98414cebc0
Revises: 93725d20f346
Create Date: 2025-05-08 08:39:08.759298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c98414cebc0'
down_revision: Union[str, None] = '93725d20f346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_suppliers')
    op.add_column('products', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('supply_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('last_supply_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'products', 'suppliers', ['supplier_id'], ['id'])
    op.add_column('suppliers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('suppliers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('suppliers', 'contact_person',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('suppliers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('suppliers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('suppliers', 'address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    op.create_unique_constraint(None, 'suppliers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.alter_column('suppliers', 'address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('suppliers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('suppliers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('suppliers', 'contact_person',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('suppliers', 'updated_at')
    op.drop_column('suppliers', 'created_at')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'last_supply_date')
    op.drop_column('products', 'supply_price')
    op.drop_column('products', 'supplier_id')
    op.create_table('product_suppliers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supply_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('last_supply_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_suppliers_product_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='product_suppliers_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_suppliers_pkey')
    )
    # ### end Alembic commands ###
