"""add nested sets

Revision ID: f0b49d9b53fe
Revises: 9f128497dfc3
Create Date: 2025-05-23 02:59:33.217329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b49d9b53fe'
down_revision: Union[str, None] = '9f128497dfc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('lft', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('rgt', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_categories_lft'), 'categories', ['lft'], unique=False)
    op.create_index(op.f('ix_categories_rgt'), 'categories', ['rgt'], unique=False)
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_rgt'), table_name='categories')
    op.drop_index(op.f('ix_categories_lft'), table_name='categories')
    op.drop_column('categories', 'rgt')
    op.drop_column('categories', 'lft')
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###
